### ISSUE TITLE
Installer and online editing

### ISSUE THREAD

**Issue by remb0** [allan-gam/ideAlarm#10]
It would be nice to install from the online editor so people without ssh winscp knowledge can install and edit scripts.

maybe it's possible to make an script that users must paste into there online editor with a os.execute that git clone/pulls the files.
Otherwise 1 time an installation from ssh is also not the problem.

but the config file and helper are really useful to have them in the online editor.
- automatically backupped
- always editable (when you are at an location that doesn't allow ssh or something)
- no need to have other tools to edit

**Comment by allan-gam** [comment]
That **might** be possible starting from ideAlarm version 2.1.0. if keeping the original file names. ideAlarm is depending on including modules by specific names.

It's worth mentioning though that the Wiki won't cover using the online editor for installing and maintaining ideAlarm.
