### ISSUE TITLE
temporary functions with SSL setup

### ISSUE THREAD

**Issue by rbiez** [allan-gam/ideAlarm#11]
Im having problem making the script edit "Z1 Arming mode" and "Z1 Status" text dummies as long as my setup is with SSL/433 access only, ive made my own custom fix. Not sure if its a bug/issue or its just my setup. Im running running domoticz on rpi3 with last stable release on raspian jessie lite.

Here's my fix:
Change the following code in ideAlarmModule.lua
`-- BELOW ARE 3 TEMPORARY FUNCTIONS THAT WILL BE OBSOLETE WHEN DZVENTS 2.3.0 IS RELEASED
-- Then the state change of a text device will trigger the Domoticz eventsystem
local function jsonAPI(apiCall, delay)
	local domoticzHost = '<my-rpi-local-ip>' --127.0.0.1 is not working for me
	local domoticzPort = '443'
	delay = delay or 0
	local url = 'https://<username>:<password>@'..domoticzHost..':'..domoticzPort..'/json.htm?'
	os.execute('(sleep '..delay..';curl -s -k "'..url..apiCall..'" > /dev/null)&')
end
`
The changes include
- Local IP of my rpi instead of 127.0.0.1
- Port 443 instead of 8080
- local url include https, username and password for domoticz
- curl include the tak -k to allow local ip instead of having to send traffic through my public domain address.

**Comment by allan-gam** [comment]
It's good that you've found how to make it work for your installation. Just keep in mind that your changes will disappear if upgrading ideAlarm. I don't do anything about this because it will be solved when we get dzVents 2.3.0.

Thanks for sharing.

**Comment by allan-gam** [comment]
Thinking about it a bit further. This can be improved. The IP, protocol and port won't be hard coded  in version 2.0.2 which I will release in a few minutes. You would have to define your local IP as "Local Networks (no username/password):" in the Domoticz settings though. That will make the usage of username and password redundant. Thanks!

**Comment by allan-gam** [comment]
Fixed
