### ISSUE TITLE
Error in Domoticz log

### ISSUE THREAD

**Issue by jsiegmund** [allan-gam/ideAlarm#14]
Hi! I'm getting this error in Domoticz logs, not sure what could be wrong: 

```
2018-01-18 22:17:53.541 Error: dzVents: Error: ideAlarm V2.1.1: An error occured when calling event handler ideAlarm
2018-01-18 22:17:53.541 Error: dzVents: Error: ideAlarm V2.1.1: ...e/pi/domoticz/scripts/dzVents/scripts/ideAlarmModule.lua:327: attempt to index a nil value
```

The alarm does trigger, it seems killing it again is the problem here. Alarm config can be found in my own repo: https://github.com/jsiegmund/domoticz-dzvents

**Comment by allan-gam** [comment]
You might have configured an alertDevice  that does not exist in Domoticz.

`alertDevices={'SRN01', 'SRN02'}`

**Comment by jsiegmund** [comment]
Nope, both devices are configured. There's one device not active (online), can that be it?

**Comment by allan-gam** [comment]
From the Wiki:
> alertDevices: (Elements are Optional) A Lua table containing the named Domoticz devices that shall be automatically switched on during an alert situation. Typically you put your siren devices names here but it can actually be any kind of Domoticz devices that can be switched "On" and "Off". If you have no alert devices or you'd like to control them using custom logic you should supply an empty table {}

I don't know what you mean by a Domoticz device being active (online). Anyway it must be a device that has been set to used. As you've seen from the Wiki, it should be a device that you can switch on/off

If you make a test dzVents script and issue these commands, do you get any errors?

`domoticz.devices('SRN01').toggleSwitch().silent()`
`domoticz.devices('SRN02').toggleSwitch().silent()`

That is what the ideAlarmModule.lua is trying to do at line :327.

**Comment by jsiegmund** [comment]
Ok found it I think... I had the siren module configured as type X10 Siren in Domoticz. For some reason that means you cannot switch it from the app any more, although you can still turn it on/off via the normal web UI. This must somehow interfere with the API call that are allowed. Once I switched it back to a normal on/off switch, it started working. Case closed!
