### ISSUE TITLE
Upgrade to dzVents 2.4.1 generate an error in ideAlarm.lua

### ISSUE THREAD

**Issue by emme73** [allan-gam/ideAlarm#15]
After ugrading to dzVents 2.4.1 got an error in ideAlarm:
`2018-01-25 14:16:00.277 dzVents: Error (2.4.1): ideAlarm V2.1.0: An error occured when calling event handler ideAlarm
2018-01-25 14:16:00.277 dzVents: Error (2.4.1): ideAlarm V2.1.0: /home/pi/domoticz/scripts/dzVents/scripts/ideAlarm.lua:32: attempt to concatenate field 'state' (a nil value)`

I assume the error appear when the script is trggered by timer (as per dzVents, now Timer is moved to the second argument of execute = function(domoticz, device)
as workaround (not really a fix) I've closed row 32 into an if statement:
`if not device.isTimer then
   ...
end`

**Comment by allan-gam** [comment]
Thanks. 
ideAlarm has been updated to version 2.4.0 to work with latest version of dzVents.
