### ISSUE TITLE
WIKI script installation comments

### ISSUE THREAD

**Issue by remb0** [allan-gam/ideAlarm#3]
Maybe it's handy to post the linux commands to make folder set chmod and wget example file?
ideAlarmConfig.lua
alarm.lua

or use http json command to make sensors/switches.

Or better:
Why the alarm.lua not with the online editor? It also saved to scripts but handier to edit?
maybe we can ask dannybloe to implement that the online editor aso monitors the modules directory. (other color)    so everything can set without the technical knowledge :)

I suggest that when creating virtual devices you create virtual hardware (ideAlarm) so all devices used for alarm are easy to filter in the device list.

**Comment by allan-gam** [comment]
Thanks.
I've updated the wiki with Linux commands. (They may differ on different Linux systems though).

We can make the sensors using http json commands but those commands use the hardware ID for the dummy device. I believe it's too hard to explain.

The ideAlarm.lua (in scripts folder) could instead be a generated script using the built in editor but this file is never changed. It's just downloaded and will be replaced when upgrading. 

It would be nice if @dannybloe could distribute an empty modules folder so we and others don't have to create it if we need to load modules. Of course it would be nice also to make the built in editor see the modules folder as well but maybe it would be hard to explain for beginners why that folder exists and what to do with it.

Your idea about a hardware device for ideAlarm is nice. I will add that in the wiki now.
