### ISSUE TITLE
ideAlarmModule.lua not found

### ISSUE THREAD

**Issue by remb0** [allan-gam/ideAlarm#4]
ideAlarm uses:
local alarm = require "ideAlarmModule"

when you follow the installation wiki this file doesn't excists.

So I downloaded it and placed it in modules, after restarting still:

no field package.preload['ideAlarmModule']
no file '/home/pi/domoticz/scripts/dzVents/modules/ideAlarmModule.lua'
no file '/usr/local/share/lua/5.2/ideAlarmModule.lua'
no file '/usr/local/share/lua/5.2/ideAlarmModule/init.lua'
no file '/usr/local/lib/lua/5.2/ideAlarmModule.lua'
no file '/usr/local/lib/lua/5.2/ideAlarmModule/init.lua'
no file './ideAlarmModule.lua'
no file '/home/pi/domoticz/scripts/dzVents/ideAlarmModule.lua'
no file '/home/pi/domoticz/scripts/dzVents/runtime/ideAlarmModule.lua'
no file '/home/pi/domoticz/scripts/dzVents/runtime/device-adapters/ideAlarmModule.lua'
no file '/home/pi/domoticz/scripts/dzVents/dzVents/ideAlarmModule.lua'
no file '/home/pi/domoticz/scripts/dzVents/scripts/ideAlarmModule.lua'
no file '/home/pi/domoticz/scripts/dzVents/generated_scripts/ideAlarmModule.lua'
no file '/home/pi/domoticz/scripts/dzVents/data/ideAlarmModule.lua'
no file '/home/pi/domoticz/scripts/dzVents/ideAlarmModule.lua'
no file '/home/pi/domoticz/scripts/dzVents/ideAlarmModule.lua'
no file '/usr/local/lib/lua/5.2/ideAlarmModule.so'
no file '/usr/local/lib/lua/5.2/loadall.so'
no file './ideAlarmModule.so'

latest beta, the fix you adviced   all on a raspberry pi 3

**Comment by allan-gam** [comment]
What are the file permissions for /home/pi/domoticz/scripts/dzVents/modules/ideAlarmModule.lua and for the directory /home/pi/domoticz/scripts/dzVents/modules ?

**Comment by remb0** [comment]
error is gone:  user was root.
please add to the wiki

great!

**Comment by allan-gam** [comment]
I assume it all was because you logged in as root (or used the sudo command) when you created the folder and the file. 
Wiki has been updated.
