### ISSUE TITLE
Do we need bi-directional sync between ideAlarm and the Domoticz Security Panel

### ISSUE THREAD

**Issue by allan-gam** [allan-gam/ideAlarm#6]
Currently we have only implemented one way syncing. Which way syncing shall occur is set in the configuration. 

Is that good or is it bad? Is one-way syncing ever relevant? Should bi-directional syncing be default?

Bi-directional syncing is somewhat complicated to implement but I can have a look at it if it's desired.

**Comment by remb0** [comment]
bi-directional is the way to go I think.
Because you can choose to use zipato keypad,  but also scripts telephone etc.  it's more flexible.

**Comment by allan-gam** [comment]
I will release an update within a moment.
