### ISSUE TITLE
deactivate

### ISSUE THREAD

**Issue by remb0** [allan-gam/ideAlarm#7]
I'm in a testfase right now and choose to let the light burn, but I have to leave because of work my wife is at home.  and I can't deactivate the alarmlogic simple off.

when the config is in the internal editor I can deactivate the scripts real fast.
and when idealarm isn't in the script folder but placed in the internal editor it's also on disk in the folder generated scripts  but also automatically backupped.

it's easier to config I think. and on work I can't access my script on disk only in the editor :P

**Comment by allan-gam** [comment]
You should be able to remove scripts/ideAlarm.lua and make an internal script instead.
